language: python
env:
  global:
    - DATABASE_URL='postgres://postgres@localhost/user_management'
  matrix:
    - TOX_ENV=py27-django16
    - TOX_ENV=py27-django17
    - TOX_ENV=py27-django18
    - TOX_ENV=py33-django16
    - TOX_ENV=py33-django17
    - TOX_ENV=py33-django18
    - TOX_ENV=py34-django16
    - TOX_ENV=py34-django17
    - TOX_ENV=py34-django18
    - TOX_ENV=py27-djangopre
    - TOX_ENV=py34-djangopre
matrix:
  fast_finish: true
  allow_failures:
    - env: TOX_ENV=py27-djangopre
    - env: TOX_ENV=py34-djangopre
install:
  - psql -c 'CREATE DATABASE user_management' -U postgres;
  - pip install -U pip
  - pip install tox==1.9.0 coveralls
script:
  - tox -e $TOX_ENV
after_success:
  coveralls
notifications:
  email: false
deploy:
  provider: pypi
  user: incuna
  on:
    condition: $TOX_ENV=py34-django17
    tags: true
  password:
    secure: DBkb54BXJe8FZ9Zp91VWOgDE3UjQ3ZHwPXJxLuSZWoUrluHbyE7ANdD3mbS+M97Ux7kfxRHpl1lSxZUe2ppMdl4Sl4hm5iVvdZkTc1ErmeJTDExMnK9E+4FDFj4UXTtGYQ1atTtE2cR8Dpbf0j3MchjiKBROOytNEUbYQfGnxEU=
  distributions: "sdist bdist_wheel"
